### ISSUE TITLE
Method subMinutes does not exist

### ISSUE THREAD

**Issue by dathwa** [LaraBug/oc-larabug-plugin#3]
Hi.
Tried installing and this happens. `"Method subMinutes does not exist." on line 96 of /vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php`.

Tried `php artisan plugin:remove Larabug.Larabug` but get this: `Call to undefined method Illuminate\View\Compilers\BladeCompiler::include()`.
The project is now broken. Any ideas?
Thank-you

**Comment by dathwa** [comment]
Here's the full trace if it helps.
`[2020-11-20 08:48:47] local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Illuminate\View\Compilers\BladeCompiler::include() in \public_html\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php:221
Stack trace:
#0 \public_html\plugins\larabug\larabug\vendor\larabug\larabug\src\ServiceProvider.php(43): Illuminate\Support\Facades\Facade::__callStatic('include', Array)
#1 [internal function]: LaraBug\ServiceProvider->boot()
#2 \public_html\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(29): call_user_func_array(Array, Array)
#3 \public_html\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#4 \public_html\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(October\Rain\Foundation\Application), Array, Object(Closure))
#5 \public_html\vendor\laravel\framework\src\Illuminate\Container\Container.php(549): Illuminate\Container\BoundMethod::call(Object(October\Rain\Foundation\Application), Array, Array, NULL)
#6 \public_html\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(792): Illuminate\Container\Container->call(Array)
#7 \public_html\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(775): Illuminate\Foundation\Application->bootProvider(Object(LaraBug\ServiceProvider))
#8 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(LaraBug\ServiceProvider), 27)
#9 \public_html\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(776): array_walk(Array, Object(Closure))
#10 \public_html\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\BootProviders.php(17): Illuminate\Foundation\Application->boot()
#11 \public_html\vendor\october\rain\src\Foundation\Application.php(85): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(October\Rain\Foundation\Application))
#12 \public_html\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(162): October\Rain\Foundation\Application->bootstrapWith(Array)
#13 \public_html\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(146): Illuminate\Foundation\Http\Kernel->bootstrap()
#14 \public_html\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#15 \public_html\index.php(43): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#16 {main}  
[2020-11-20 08:50:14] local.ERROR: BadMethodCallException: Method subMinutes does not exist. in \public_html\vendor\laravel\framework\src\Illuminate\Support\Traits\Macroable.php:96
Stack trace:
#0 \public_html\vendor\laravel\framework\src\Illuminate\Session\FileSessionHandler.php(70): Illuminate\Support\Carbon->__call('subMinutes', Array)
#1 \public_html\vendor\laravel\framework\src\Illuminate\Session\Store.php(96): Illuminate\Session\FileSessionHandler->read('o0W6dEpMfUxiCEd...')
#2 \public_html\vendor\laravel\framework\src\Illuminate\Session\Store.php(86): Illuminate\Session\Store->readFromHandler()
#3 \public_html\vendor\laravel\framework\src\Illuminate\Session\Store.php(70): Illuminate\Session\Store->loadSession()
#4 \public_html\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(102): Illuminate\Session\Store->start()
#5 \public_html\vendor\laravel\framework\src\Illuminate\Support\helpers.php(1038): Illuminate\Session\Middleware\StartSession->Illuminate\Session\Middleware\{closure}(Object(Illuminate\Session\Store))
#6 \public_html\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(103): tap(Object(Illuminate\Session\Store), Object(Closure))
#7 \public_html\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(57): Illuminate\Session\Middleware\StartSession->startSession(Object(Illuminate\Http\Request))
#8 \public_html\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#9 \public_html\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#10 \public_html\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#11 \public_html\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#12 \public_html\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 \public_html\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(68): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#14 \public_html\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#15 \public_html\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 \public_html\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#17 \public_html\vendor\laravel\framework\src\Illuminate\Routing\Router.php(660): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#18 \public_html\vendor\laravel\framework\src\Illuminate\Routing\Router.php(635): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#19 \public_html\vendor\laravel\framework\src\Illuminate\Routing\Router.php(601): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#20 \public_html\vendor\october\rain\src\Router\CoreRouter.php(20): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#21 \public_html\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(176): October\Rain\Router\CoreRouter->dispatch(Object(Illuminate\Http\Request))
#22 \public_html\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#23 \public_html\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 \public_html\vendor\october\rain\src\Foundation\Http\Middleware\CheckForMaintenanceMode.php(25): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 \public_html\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): October\Rain\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 \public_html\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 \public_html\plugins\popcornphp\redirecttohttps\classes\HTTPSMiddleware.php(13): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#28 \public_html\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): PopcornPHP\RedirectToHTTPS\Classes\HTTPSMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 \public_html\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 \public_html\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 \public_html\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#32 \public_html\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#33 \public_html\index.php(43): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#34 {main} `

**Comment by Cannonb4ll** [comment]
@SebastiaanKloos You have any idea about this one?

**Comment by SebastiaanKloos** [comment]
@dathwa what October CMS version do you have?

**Comment by dathwa** [comment]
I have version 469 and 45 plugins.
Managed to remove the plugin and bring the site back online by editing the plugin file and removing vendor folder.

**Comment by SebastiaanKloos** [comment]
@dathwa Is the 469 based on the Laravel 6 version of October CMS (1.1.x)? Or just the 469 version based on Laravel 5.5? I think the package only works on Laravel 6. I'll test it soon and if so, change the documentation so others won't get this issue.

**Comment by SebastiaanKloos** [comment]
Let me test some things. I'll get back to you about this issue

**Comment by SebastiaanKloos** [comment]
![CleanShot 2020-11-20 at 13 30 37](https://user-images.githubusercontent.com/6506510/99800448-a9ae5380-2b34-11eb-821c-9092cb03581c.png)
 I have the same issue. I think the plugin needs Laravel 6. Will try to make a workaround as all marketplace installations are not using Laravel 6.

**Comment by SebastiaanKloos** [comment]
I'm so sorry. This plugin seems to only work with Laravel >=5.5. So for now only October CMS >=1.1.0 will work

**Comment by SebastiaanKloos** [comment]
We are prepping some work for LaraBug to support Laravel 5.5. Will post an update soon

**Comment by SebastiaanKloos** [comment]
@dathwa Could you give the new update a try? It should work

**Comment by SebastiaanKloos** [comment]
Fixed in https://github.com/LaraBug/oc-larabug-plugin/commit/3e13dceb942b5ee225f26def7632a9d92414631a

**Comment by dathwa** [comment]
Yip. Got it working with Laravel 5.5. Thank-you.

**Comment by SebastiaanKloos** [comment]
> Yip. Got it working with Laravel 5.5. Thank-you.

Awesome! Enjoy using LaraBug!
